name: Test Tools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm init -y
          npm install ethers minimist @openzeppelin/contracts

      - name: Lint and Test Scripts
        run: |
          node --check verify-certification.js
          node --check vote-proposal.js

      - name: Compile Solidity Contracts
        uses: actions/setup-node@v3
        with:
          node-version: "18"
        run: |
          npm install --save-dev hardhat
          npx hardhat compile
